# Sections content configuration file
## 
### use navigation.yml file to re-order, delete or add section of each card
### here you can find all content in all pre-build sections

### About [ about ]
about:
  title: "Über mich"
  text: "
        <p>
          <strong>Hallo! Ich bin Norman Albusberger.</strong><br>IT Spezialist und Volkswirt, Ich habe umfangreiche Erfahrung im Bereich Unternehmensführung, strategischem Management und verfüge über 20 Jahre Erfahrung im Bereich Softwareentwicklung.
        </p>
        "
  list:
    - label: "Wohnort"
      value: "Berlin-Brandenburg, Deutschland"

    - label: "Freelance"
      value: "Verfügbar nach Terminabsprache <a class=\"button\" href=\"#\" onclick=\"Calendly.initPopupWidget({url: 'https://calendly.com/norman-albusberger/15min'});return false;\">Termin vereinbaren</a>"

### Services [ services ]
services:
  title: "Leistungen"
  items:
    - icon: "code"
      name: "Full-Stack Web Entwicklung"
      text: "Ich setze moderne aber auch erprobte Technologien ein, berücksichtige den Lebenszyklus und die Qualität eingesetzter Open Source Technologien."
      h_line: 1

    - icon: "speakerphone"
      name: "Strategische Beratung"
      text: "Digitalisierung bedeutet weit mehr als neue IT-Systeme. Wer Potenziale nutzen will, muss den Trade-off zwischen technologischen Möglichkeiten und betriebswirtschaftlicher Notwendigkeit beherrschen – und den Menschen mitnehmen."
      h_line: 1

    - icon: "alert"
      name: "Interimsmanagement"
      text: "Weg von klassischen Management-Methoden hin zu agilen, autonomen und Aufgaben-orientierten Organisationen."
      h_line: 0

    - icon: "ios-book"
      name: "Coaching & Trainings"
      text: "Eine der für mich wichtigsten Management-Fähigkeiten ist das Mentoring. Ich teile gern mein Know-How in den unterschiedlichen Bereichen. Ich stehe daher auch gesondert für Lehraufträge und Coachings zur Verfügung."

### Pricing [ pricing ]
pricing:
  title: "Pricing"
  items:
    - icon: "speedometer speed-basic"
      name: "Basic"
      price_pre: "$"
      price: "22"
      price_after: "hour"
      list:
        - text: "Web Development"
          disable: 0
          new: 0

        - text: "Advetising"
          disable: 0
          new: 0

        - text: "Game Development"
          disable: 0
          new: 0

        - text: "Music Writing"
          disable: 1
          new: 0

        - text: "Photography"
          disable: 1
          new: 1
      button_link: "#"
      button_text: "Buy Basic"

    - icon: "speedometer"
      name: "Pro"
      price_pre: "$"
      price: "48"
      price_after: "hour"
      list:
        - text: "Web Development"
          disable: 0
          new: 0

        - text: "Advetising"
          disable: 0
          new: 0

        - text: "Game Development"
          disable: 0
          new: 0

        - text: "Music Writing"
          disable: 0
          new: 0

        - text: "Photography"
          disable: 0
          new: 1
      button_link: "#"
      button_text: "Buy Pro"

### Facts [ facts ]
facts:
  title: "Fun Fact"
  items:
    - icon: "disc"
      name: "80 Albumes Listened"

    - icon: "trophy"
      name: "15 Awards Won"

    - icon: "coffee"
      name: "1 000 Cups of coffee"

    - icon: "flag"
      name: "10 Countries Visited"

### Clients [ clients ]
clients:
  title: "Clients"
  items:
    - url: "https://www.google.com"
      image: "assets/img/clients/client_1.png"

    - url: "https://www.google.com"
      image: "assets/img/clients/client_2.png"

    - url: "https://www.google.com"
      image: "assets/img/clients/client_3.png"

    - url: "https://www.google.com"
      image: "assets/img/clients/client_4.png"

### Testimonials [ testimonials ]
testimonials:
  title: "Testimonials"
  items:
    - image: "assets/img/man1.jpg"
      name: "Helen Floyd"
      subname: "Art Director"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit."

    - image: "assets/img/man1.jpg"
      name: "Robert Chase"
      subname: "CEO"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit."

    - image: "assets/img/man1.jpg"
      name: "Helen Floyd"
      subname: "Art Director"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit."

### Resume [ resume ]
resume:
  title: "Curiculum Vitae"
  experience:
    title: "Tätigkeiten"
    icon: "briefcase"
    items:
      - year: "2021 - jetzt"
        role: "Senior Developer"
        company: "Fatchip GmbH"
        text: ""
        active: 1
        h_line: 1

      - year: "2016 - jetzt"
        role: "Management Consultant (Mandat)"
        company: "Solfas Technologie GmbH."
        text: "CEO Advisory und Coaching, Strategisches Marketing, Produkt-Portfolio Analyse, Coaching in agilen Methoden mit Standard-Werkzeugen, Requirementsengineering, Scrum Master, Softwareentwicklung"
        active: 1
        h_line: 1

      - year: "2020 - 2021"
        role: "Frontend-Engineering"
        company: "Babymarkt GmbH"
        text: "Unterstützung des Frontend-Teams bei der Softwareentwicklung"
        active: 0
        h_line: 0

      - year: "2006 - 2016"
        role: "Executive Partner, CTO"
        company: "PRofiFLITZER GmbH"
        text: "Unternehmensführung und Leitung der technischen Entwicklung"
        active: 0
        h_line: 1



  education:
    title: "Ausbildung"
    icon: "university"
    items:
      - year: "2015"
        institution: "Technische Universität"
        city: "Berlin"
        text: "Diplom in Volkswirtschaftslehre mit Schwerpunkt Netzwerk -und Informationsgüterökonomik und Infrastruktur-Management"

      - year: "2000"
        institution: "Berliner Lokalnachrichten"
        city: "Berlin"
        text: "6-monatiges Praktikum im Verlagsgeschäft als Redakteur"
        h_line: 1

      - year: "1998-1999"
        institution: "Bundeswehr"
        city: "Schleswig-Holstein"
        text: "Militärdienst im Hauptquartier der alliierten Landstreitkräfte Schleswig-Holstein und Jütland"
        h_line: 0

### Skills [ skills ]
skills:
  title: "Kenntnisse"
  columns:
    - type: "circles" #skills progress type - default, dotted, circles, list
      title: "Programmiersprachen"
      icon: "code"
      items:
        - label: "PHP"
          value: "100" #0-100 progress in %

        - label: "JavaScript"
          value: "100" #0-100 progress in %

        - label: "C#"
          value: "70"

        - label: "Python"
          value: "50" #0-100 progress in %

    - type: "default" #skills progress type - default, dotted, circles, list
      title: "Frameworks/Bibliotheken"
      icon: "code"
      items:
        - label: "Symfony 5"
          value: "100" #0-100 progress in %

        - label: "jQuery"
          value: "100" #0-100 progress in %

        - label: "Bootstrap 3,4,5"
          value: "100"

        - label: "Mongoose"
          value: "80" #0-100 progress in %

        - label: ".net"
          value: "80" #0-100 progress in %

        - label: "Express Node.js"
          value: "100" #0-100 progress in %

    - type: "circles" #skills progress type - default, dotted, circles, list
      title: "API"
      icon: "code"
      items:
        - label: "REST"
          value: "100" #0-100 progress in %

        - label: "GraphQL"
          value: "70" #0-100 progress in %

        - label: "OpenAPI/Swagger"
          value: "80" #0-100 progress in %

    - type: "default"
      title: "Datenbanken"
      icon: "easel"
      items:
        - label: "mySQL"
          value: "100" #0-100 progress in %

        - label: "MongoDB"
          value: "95" #0-100 progress in %

        - label: "SQLLite"
          value: "60" #0-100 progress in %

        - label: "MS-SQL-Server"
          value: "80" #0-100 progress in %

    - type: "default" #skills progress type - default, dotted, circles, list
      title: "Markup / Stylesheet"
      icon: "easel"
      items:
        - label: "HTML5"
          value: "100" #0-100 progress in %

        - label: "CSS/SCSS"
          value: "95" #0-100 progress in %

        - label: "Yaml/Markdown/JSON"
          value: "100" #0-100 progress in %

        - label: "XAML"
          value: "75" #0-100 progress in %

        - label: "Latex"
          value: "75" #0-100 progress in %

    - type: "dotted" #skills progress type - default, dotted, circles, list
      title: "Sprachen"
      icon: "flag"
      items:
        - label: "Englisch"
          value: "90" #0-100 progress in %

        - label: "Deutsch"
          value: "100" #0-100 progress in %

        - label: "Russisch"
          value: "20" #0-100 progress in %


    #- type: "list" #skills progress type - default, dotted, circles, list
    #  title: "Weitere Kentnisse"
    #  icon: "android-list"
    #  items:
    #    - label: ""
    #      value: "" #0-100 progress in %
#
#        - label: "iOS and android apps"
#          value: "" #0-100 progress in %
#
#        - label: "Create logo design"
#          value: "" #0-100 progress in %
#
#        - label: "Design for print"
#          value: "" #0-100 progress in %
#
#        - label: "Modern and mobile-ready"
#          value: "" #0-100 progress in %
#
#        - label: "Advertising services include"
#          value: "" #0-100 progress in %
#
#        - label: "Graphics and animations"
#          value: "" #0-100 progress in %
#
#        - label: "Search engine marketing"
#          value: "" #0-100 progress in %

### Portfolio [ portfolio ]
portfolio:
  title: "Aktuelle Arbeiten"
  filters:
    - name: "All"
      slug: "grid-item"
      active: 1

    - name: "Beratung"
      slug: "consulting"
      active: 0

    - name: "Softwareentwicklung"
      slug: "video"
      active: 0

### Blog [ blog ]
blog:
  title: "Latest Posts"

### Contact Info List [ contacts-info ]
contacts_info:
  title: "Kontakt"
  list:
    - label: "Addresse"
      value: "Berlin/Brandenburg, Deutschland"

    - label: "Email"
      value: "norman.albusberger@icloud.com"

    - label: "Telefon"
      value: "+4917657912348"

### Contact Form [ contacts-form ]
contacts_form:
  title: "Kontakt-Formular"
